import { Children, cloneElement, isValidElement, ReactNode } from 'react';
import styled from 'styled-components';

export type ShowcaseProps = {
  variations:
    | string[]
    | { [key: string]: string | number | boolean | undefined }[];
  propName: string;
  showLabel?: boolean;
} & { children: ReactNode };

const VariationsContainer = styled.div<{ children: any }>`
  display: flex;
  gap: 2rem;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: start;
  /* box-shadow: rgba(149, 157, 165, 0.2) 0 8px 24px; */
  padding: 2rem;
`;

const El = styled.div<{ children: any }>`
  display: flex;
  margin: 0.5rem;
  text-align: center;
  flex-direction: column;
  align-items: center;
  min-width: 20%;
  max-width: 100%;
`;

export const ShowcaseElements = ({
  children,
  propName,
  variations,
  showLabel = true,
}: ShowcaseProps) => {
  return variations.map(
    (
      variation:
        | string
        | { [key: string]: string | number | boolean | undefined },
      idx: number
    ) => {
      const adjustedChildren = Children.map(children, (child) => {
        if (isValidElement(child)) {
          return cloneElement(child, { ...child.props, [propName]: variation });
        }
        return child;
      });

      const getVariantLabel = (): string => {
        if (typeof variation === 'string')
          return variation[0].toUpperCase() + variation.slice(1);
        if (typeof variation === 'object')
          return (
            propName[0].toUpperCase() +
            propName.slice(1) +
            ': ' +
            Object.values(variation).join(' ') // JSON.stringify(Object.values(variation)[0])
          );
        return `Case ${idx + 1}`;
      };

      const variationLabel = getVariantLabel();

      return (
        <El key={idx}>
          {adjustedChildren}
          <br />
          {showLabel ? variationLabel : ''}
        </El>
      );
    }
  );
};

export type VariantsType = Array<
  | string
  | number
  | boolean
  | { [key: string]: string | number | boolean | undefined | (() => void) }
>;

export type ShowcaseProps2<T> = {
  variations: T;
  propName: string;
  showLabel?: boolean;
  options?: GetVariantLabelOptions;
} & { children: ReactNode };

type GetVariantLabelOptions = {
  showPropName?: boolean;
  limitWordCount?: number;
};
/**
 * Returns a human-readable label for a given variant.
 *
 * @param {T[number]} variation - The variant to generate a label for.
 * @param {string} propName - The name of the property being varied.
 * @param {GetVariantLabelOptions} [options] - Options for customizing the label.
 * @return {string} A human-readable label for the variant.
 */
const getVariantLabel = <T extends VariantsType>(
  variation: T[number],
  propName: string,
  options: GetVariantLabelOptions = { showPropName: true }
): string => {
  const variationString =
    typeof variation !== 'object'
      ? JSON.stringify(variation)
      : JSON.stringify(Object.values(variation));
  const descriptions = variationString
    .split(/[^\w\d]/g)
    .filter((w) => !!w)
    .map((w) => w[0].toUpperCase() + w.slice(1));
  const variationDescription = options.limitWordCount
    ? descriptions.slice(0, options.limitWordCount).join(' ')
    : descriptions.join(' ');
  if (options.showPropName) {
    return (
      propName[0].toUpperCase() +
      propName.slice(1) +
      ': ' +
      variationDescription
    );
  }
  return variationDescription;
};

/**
 * Returns an array of JSX elements, each representing a variant of the given component.
 * The variants are generated by mapping over the provided variations and applying each one to the component.
 *
 * @param {ReactNode} children - The component to be varied.
 * @param {string} propName - The name of the property to be varied.
 * @param {T} variations - The variations to be applied to the component.
 * @param {boolean} [showLabel=true] - Whether to display a label for each variant.
 * @param {GetVariantLabelOptions} [options={ showPropName: true }] - Options for customizing the variant labels.
 * @return {JSX.Element[]} An array of JSX elements, each representing a variant of the component.
 */
export const ShowcaseElements2 = <T extends VariantsType>({
  children,
  propName,
  variations,
  showLabel = true,
  options = { showPropName: true },
}: ShowcaseProps2<T>): JSX.Element[] => {
  return variations.map((variation: T[number], idx: number): JSX.Element => {
    const ComponentVariant = Children.map(children, (child) => {
      if (isValidElement(child)) {
        return cloneElement(child, { ...child.props, [propName]: variation });
      }
      return child;
    });

    return (
      <El key={idx}>
        {ComponentVariant}
        <br />
        {showLabel ? getVariantLabel(variation, propName, options) : ''}
      </El>
    );
  });
};

/**
 * A container component that showcases a given React component with various props.
 *
 * @param {JSX.Element[]} children - The React components to be showcased.
 * @return {JSX.Element} A JSX element containing the showcased components.
 */
export const ShowcaseContainer = ({
  children,
}: {
  children: JSX.Element[];
}) => <VariationsContainer>{children}</VariationsContainer>;

/**
 * A higher-order component that showcases a given React component with various props.
 *
 * @param {ReactNode} Component - The React component to be showcased.
 * @param {string} propName - The name of the prop to be varied.
 * @param {VariantsType} variations - An array of values for the varied prop.
 * @param {boolean} [showLabel] - Whether to show a label for each variation.
 * @param {GetVariantLabelOptions} [options] - Options for customizing the label.
 * @return {JSX.Element} A JSX element containing the showcased component.
 */
export const withComponentShowcase =
  (Component: ReactNode) =>
  (
    propName: ShowcaseProps['propName'],
    variations: VariantsType,
    showLabel?: ShowcaseProps['showLabel'],
    options?: GetVariantLabelOptions
  ): JSX.Element =>
    (
      <ShowcaseContainer>
        {ShowcaseElements2({
          children: Component,
          propName,
          variations,
          showLabel,
          options,
        })}
      </ShowcaseContainer>
    );

export const GeneralShowcaseTemplate = (
  Component: ReactNode,
  propName: ShowcaseProps['propName'],
  variations: ShowcaseProps['variations'],
  showLabel?: ShowcaseProps['showLabel'],
  options?: GetVariantLabelOptions
) => withComponentShowcase(Component)(propName, variations, showLabel, options);
